version: '3'
services: 
  postgres: 
     image: 'postgres:latest'
  redis:    
     image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev  
      context:  ./nginx
    ports:   
      - '3050:80'
  api:
    build:  # specify build - building server image
      dockerfile: Dockerfile.dev
      context: ./server    #find a folder named server and and build the docker file from there 
    volumes:               #specify volumes
        - /app/node_modules
        - ./server:/app
    environment:  # setting env variables
        - REDIS_HOST=redis    
        - REDIS_PORT=6379  
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password #default passwd 
        - PGPORT=5432 
#adding worker and client services
  client:     
    build:
       dockerfile:  Dockerfile.dev
       context:    ./client
    volumes: 
       - /app/node_modules
       - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app          